### PR TITLE
Feature/canonicalization

### PR DESCRIPTION
**Pull request by rlskoeser**
Adding canonicalization logic to the image parameters that need it, based on the spec (as best as I can understand it).

Did some comparisons with what piffle is generating and what Loris returns for canonical headers, think it seems reasonable.  The Loris code has a lot more checking and logic in the canonicalization, but I think that's because it has to do actual image size calculation and error handling that aren't needed in piffle.

### CODE REVIEW

**Comment by jpstroop** [comment]
>  The Loris code has a lot more checking and logic in the canonicalization, but I think that's because it has to do actual image size calculation and error handling that aren't needed in piffle.

I'm sure that's correct, e.g. out-of-bounds regions are OK (as long as both the x and y are in bounds and w and h are > 0), but the spec is silent about whether a server should redirect or just serve images from the URL.

As an aside, I've been working on [this](https://github.com/jpstroop/loris-redux/tree/master/loris/parameters) and have wondered whether could be leveraged in there somehow--maybe I could extract my parameter stuff into a separate dependency or something.

**Comment by rlskoeser** [comment]
@jpstroop thanks for the feedback!  I've been looking at the loris code some as I worked on this stuff and trying to understand the spec on canonicalization.  I did notice a fair bit of overlap between what I'm doing in piffle and some of the loris parameter logic.   Hadn't noticed loris-redux yet, will have to check that out!  The new parameter objects look very nice (especially after I was just looking at the much more complicated ones in loris).

I do think that the loris parameter logic could be valuable as a separate dependency.   (Maybe piffle goes away in that case, or gets a lot smaller...)

Do you think I should add checks to my canonicalization logic for this?
> out-of-bounds regions are OK (as long as both the x and y are in bounds and w and h are > 0)

I've thought about adding more validation to the parsing options, to prevent invalid options from getting set to begin with (like negative dimensions), but haven't added it yet.

Do you know of a good way to check my canonicalization logic?  I manually compared what Loris returns for the canonical value against what I'm generating with piffle for a few different cases (and caught one problem), but I suspect I'm still missing some cases.

**Comment by jpstroop** [comment]
Sorry for the delay.

> Do you know of a good way to check my canonicalization logic?

I guess I don't, beyond what you're already doing, i.e. break up the tests so that you can try to cover all of your bases parameter by parameter. That's what I've done as well, e.g. in [`TestRegionParameter`](https://github.com/jpstroop/loris-redux/blob/f18955a4d6bc29a388b39ee00b7fbf41260f1fbb/tests/loris/parameters/region_tests.py), you'll see:

```python
rp = RegionParameter('square', features, info_data)
assert rp.request_type is REGION_SQUARE
assert rp.canonical == '0,1281,4638,4638' # <----
```
Whenever it makes sense, and a similar pattern for each type of request as well as some common errors.

**Comment by rlskoeser** [comment]
@jpstroop thanks for the feedback.  My concern was more that I'm misinterpreting the spec or missing some subtlety.  Maybe I'll check out your parameter tests and compare them to piffle canonicalization as a sanity check.

**Pull request merged**
